# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autologin',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('extno', models.CharField(max_length=10)),
                ('userno', models.CharField(max_length=10)),
                ('sx', models.CharField(max_length=4, blank=True)),
            ],
            options={
                'db_table': 'autologin',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Businessgroup',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('groupid', models.CharField(max_length=4, blank=True)),
                ('groupname', models.CharField(max_length=20, blank=True)),
                ('callno', models.TextField(blank=True)),
                ('vocname', models.TextField(blank=True)),
                ('useivr', models.CharField(max_length=1, blank=True)),
                ('directto', models.CharField(max_length=20, blank=True)),
                ('filepath', models.CharField(max_length=200, blank=True)),
                ('vocprompt', models.CharField(max_length=20, blank=True)),
                ('sourcetype', models.CharField(max_length=1, blank=True)),
            ],
            options={
                'db_table': 'businessgroup',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BusinessTransferplan',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('groupid', models.CharField(max_length=10, blank=True)),
                ('starttime', models.CharField(max_length=20, blank=True)),
                ('endtime', models.CharField(max_length=20, blank=True)),
                ('tansfertype', models.CharField(max_length=1, blank=True)),
                ('transferwhere', models.CharField(max_length=20, blank=True)),
            ],
            options={
                'db_table': 'business_transferplan',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallCallevaluate',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('evaluateid', models.CharField(max_length=2)),
                ('evaluatename', models.CharField(max_length=30)),
                ('bzbz', models.CharField(max_length=200, blank=True)),
            ],
            options={
                'db_table': 'call_callevaluate',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallCalloutlineinfo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('lines', models.CharField(max_length=50, blank=True)),
                ('calloutno', models.CharField(max_length=50, blank=True)),
                ('callnos', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'call_calloutlineinfo',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallCallpara',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('callparaid', models.CharField(max_length=4)),
                ('callparavalue', models.CharField(max_length=120, blank=True)),
                ('callparamemo', models.CharField(max_length=200, blank=True)),
            ],
            options={
                'db_table': 'call_callpara',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallCallrecord',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('callfromdatetime', models.CharField(max_length=20)),
                ('callenddatetime', models.CharField(max_length=20)),
                ('calldurationtime', models.CharField(max_length=12)),
                ('calltype', models.CharField(max_length=2, blank=True)),
                ('callno', models.CharField(max_length=60)),
                ('calltrunckno', models.CharField(max_length=12)),
                ('calluerno', models.CharField(max_length=12, blank=True)),
                ('calldtmfno', models.CharField(max_length=60)),
                ('customername', models.CharField(max_length=60, blank=True)),
                ('username', models.CharField(max_length=30, blank=True)),
                ('callrecordid', models.CharField(max_length=60)),
                ('ucdchanno', models.IntegerField(null=True, blank=True)),
                ('ucdgroupid', models.CharField(max_length=4, blank=True)),
                ('trundatetime', models.CharField(max_length=20, blank=True)),
                ('hangupdatetime', models.CharField(max_length=20, blank=True)),
                ('gjlx', models.CharField(max_length=1, blank=True)),
                ('zjf', models.CharField(max_length=1, blank=True)),
                ('recordfilename', models.CharField(max_length=200, blank=True)),
                ('seledatetime', models.CharField(max_length=20, blank=True)),
                ('recordtype', models.CharField(max_length=2, blank=True)),
                ('recordyhbh', models.CharField(max_length=30, blank=True)),
                ('callevaluate', models.CharField(max_length=1, blank=True)),
                ('smuser', models.TextField(blank=True)),
                ('sendmessagetime', models.CharField(max_length=20, blank=True)),
                ('ifplayed', models.CharField(max_length=1, blank=True)),
                ('ringtime', models.CharField(max_length=50, blank=True)),
                ('talktime', models.CharField(max_length=50, blank=True)),
                ('cpstaskid', models.CharField(max_length=20, blank=True)),
            ],
            options={
                'db_table': 'call_callrecord',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallChan',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('channo', models.IntegerField()),
                ('chantype', models.IntegerField()),
                ('chandialno', models.CharField(max_length=20)),
                ('useivr', models.CharField(max_length=1, blank=True)),
                ('directto', models.CharField(max_length=20, blank=True)),
                ('recordflag', models.CharField(max_length=1, blank=True)),
                ('smssendtoip', models.CharField(max_length=30, blank=True)),
                ('smssendtoport', models.CharField(max_length=4, blank=True)),
                ('chanstatus', models.CharField(max_length=60, blank=True)),
                ('chancallid', models.CharField(max_length=60, blank=True)),
                ('chancallname', models.CharField(max_length=200, blank=True)),
                ('chandtmf', models.CharField(max_length=60, blank=True)),
                ('chancalldatetime', models.CharField(max_length=20, blank=True)),
                ('chanendcalldatetime', models.CharField(max_length=20, blank=True)),
                ('chandualtime', models.CharField(max_length=18, blank=True)),
                ('onlineflag', models.CharField(max_length=2, blank=True)),
                ('chanucdgroup', models.CharField(max_length=1, blank=True)),
                ('currentuser', models.CharField(max_length=30, blank=True)),
                ('chanlinkchan', models.IntegerField(null=True, blank=True)),
                ('linestatus', models.IntegerField(null=True, blank=True)),
                ('recordfileid', models.CharField(max_length=32, blank=True)),
                ('inout', models.CharField(max_length=1, blank=True)),
                ('binip', models.CharField(max_length=20, blank=True)),
                ('binport', models.CharField(max_length=5, blank=True)),
                ('ucdgroupid', models.CharField(max_length=4, blank=True)),
                ('trundatetime', models.CharField(max_length=20, blank=True)),
                ('hangupdatetime', models.CharField(max_length=20, blank=True)),
                ('card', models.IntegerField(null=True, blank=True)),
                ('hxtdjj', models.CharField(max_length=10, blank=True)),
                ('hxtchanno', models.IntegerField(null=True, blank=True)),
                ('linename', models.CharField(max_length=20, blank=True)),
                ('outdialno', models.CharField(max_length=20, blank=True)),
                ('tollno', models.CharField(max_length=20, blank=True)),
                ('mainline', models.IntegerField(null=True, blank=True)),
                ('ifmain', models.IntegerField(null=True, blank=True)),
                ('pickupno', models.CharField(max_length=20, blank=True)),
                ('mailline', models.IntegerField(null=True, blank=True)),
                ('voicename', models.CharField(max_length=20, blank=True)),
                ('dtmf', models.CharField(max_length=1, blank=True)),
                ('mainno', models.CharField(max_length=20, blank=True)),
            ],
            options={
                'db_table': 'call_chan',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallChandj',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('dspmodno', models.IntegerField()),
                ('channo', models.IntegerField()),
                ('chandialno', models.CharField(max_length=20, blank=True)),
                ('onlineflag', models.CharField(max_length=20, blank=True)),
                ('currentuser', models.CharField(max_length=30, blank=True)),
                ('useanalog', models.CharField(max_length=1, blank=True)),
                ('directto', models.CharField(max_length=20, blank=True)),
                ('catno', models.CharField(max_length=1, blank=True)),
                ('bgh', models.CharField(max_length=50, blank=True)),
                ('recordflag', models.CharField(max_length=1, blank=True)),
            ],
            options={
                'db_table': 'call_chandj',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallChanrecordings',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tapichanno', models.CharField(max_length=20)),
                ('channelhandle', models.DecimalField(decimal_places=0, max_digits=10, db_column='channelHandle')),
                ('dev', models.IntegerField()),
                ('pcm', models.IntegerField()),
            ],
            options={
                'db_table': 'call_chanrecordings',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallEnablecall',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('lx', models.CharField(max_length=1)),
                ('bh', models.CharField(max_length=10)),
                ('n_all', models.CharField(max_length=1)),
                ('n_gn', models.CharField(max_length=1)),
                ('n_gj', models.CharField(max_length=1)),
                ('n_tel', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'call_enablecall',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallHmd',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tel', models.CharField(max_length=30)),
                ('bussinessgroupid', models.CharField(max_length=4, blank=True)),
            ],
            options={
                'db_table': 'call_hmd',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallIp',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('iplist', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'call_ip',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallIvr',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ivrindex', models.CharField(max_length=20)),
                ('ivrname', models.CharField(max_length=20)),
                ('channelno', models.CharField(max_length=100, blank=True)),
                ('noticepath', models.CharField(max_length=100, blank=True)),
                ('operatetype', models.CharField(max_length=50, blank=True)),
                ('content', models.CharField(max_length=50, blank=True)),
                ('operatekey', models.CharField(max_length=50, blank=True)),
            ],
            options={
                'db_table': 'call_ivr',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallIvroperatetype',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('operatetype', models.IntegerField()),
                ('operatevalue', models.CharField(max_length=50, blank=True)),
            ],
            options={
                'db_table': 'call_ivroperatetype',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallLimitgroup',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('limitgroupid', models.CharField(max_length=4)),
                ('limitgroupname', models.CharField(max_length=30)),
                ('limitgroupdialno', models.CharField(max_length=200, blank=True)),
                ('limitgroupmemo', models.CharField(max_length=200, blank=True)),
            ],
            options={
                'db_table': 'call_limitgroup',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallLimitgroupuser',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('limitgroupid', models.CharField(max_length=4)),
                ('channo', models.IntegerField()),
            ],
            options={
                'db_table': 'call_limitgroupuser',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallOnlineflag',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('bh', models.CharField(max_length=2)),
                ('mc', models.CharField(max_length=10, blank=True)),
                ('jtdj', models.CharField(max_length=4, blank=True)),
                ('sfjt', models.CharField(max_length=1, blank=True)),
            ],
            options={
                'db_table': 'call_onlineflag',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Calloutgroupline',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('groupid', models.CharField(max_length=4)),
                ('callno', models.CharField(max_length=50)),
                ('sx', models.CharField(max_length=4, blank=True)),
            ],
            options={
                'db_table': 'calloutgroupline',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallPickupgroup',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('pickupgroupid', models.CharField(max_length=4)),
                ('pickupgroupname', models.CharField(max_length=30)),
                ('pickupgroupmemo', models.CharField(max_length=200, blank=True)),
            ],
            options={
                'db_table': 'call_pickupgroup',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallPickupgroupuser',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('pickupgroupid', models.CharField(max_length=4)),
                ('orderid', models.IntegerField()),
                ('ucdgroupid', models.CharField(max_length=4, blank=True)),
                ('type', models.CharField(max_length=1, blank=True)),
            ],
            options={
                'db_table': 'call_pickupgroupuser',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Callprocess',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=20, blank=True)),
                ('callno', models.TextField(blank=True)),
                ('vocname', models.CharField(max_length=20, blank=True)),
                ('useivr', models.CharField(max_length=1, blank=True)),
                ('directtype', models.CharField(max_length=1, blank=True)),
                ('directto', models.CharField(max_length=20, blank=True)),
                ('sourcetype', models.CharField(max_length=1, blank=True)),
                ('enterno', models.CharField(max_length=2, blank=True)),
                ('truncateplan', models.CharField(max_length=10, blank=True)),
                ('parentcode', models.CharField(max_length=4, blank=True)),
                ('type', models.CharField(max_length=1, blank=True)),
                ('memo', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'callprocess',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallRecordings',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('callfromdatetime', models.CharField(max_length=20)),
                ('callenddatetime', models.CharField(max_length=20)),
                ('calldurationtime', models.CharField(max_length=12)),
                ('inout', models.CharField(max_length=1)),
                ('callno', models.CharField(max_length=60)),
                ('calltrunckno', models.CharField(max_length=12)),
                ('calluerno', models.CharField(max_length=8)),
                ('calldtmfno', models.CharField(max_length=60, blank=True)),
                ('callrecordid', models.CharField(max_length=32, blank=True)),
                ('ucdchanno', models.CharField(max_length=20, blank=True)),
                ('hangupdatetime', models.CharField(max_length=20, blank=True)),
                ('recordfilename', models.CharField(max_length=200, blank=True)),
                ('filesize', models.DecimalField(null=True, max_digits=18, decimal_places=0, blank=True)),
            ],
            options={
                'db_table': 'call_recordings',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallRecordtype',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('recordtype', models.CharField(max_length=2)),
                ('recordname', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'call_recordtype',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallStatus',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('linestatus', models.IntegerField()),
                ('chinesestatus', models.CharField(max_length=30, blank=True)),
                ('bzbz', models.CharField(max_length=200, blank=True)),
            ],
            options={
                'db_table': 'call_status',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallStatus2',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('linestatus', models.IntegerField()),
                ('chinesestatus', models.CharField(max_length=30, blank=True)),
                ('bzbz', models.CharField(max_length=200, blank=True)),
            ],
            options={
                'db_table': 'call_status2',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallSubcallrecord',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('callfromdatetime', models.CharField(max_length=20)),
                ('callenddatetime', models.CharField(max_length=20)),
                ('calldurationtime', models.CharField(max_length=12)),
                ('calltype', models.CharField(max_length=1)),
                ('zjsxh', models.CharField(max_length=1)),
                ('calluerno', models.CharField(max_length=8)),
                ('calldtmfno', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=30, blank=True)),
                ('callrecordid', models.CharField(max_length=32)),
                ('hangupdatetime', models.CharField(max_length=20, blank=True)),
                ('gjlx', models.CharField(max_length=1, blank=True)),
            ],
            options={
                'db_table': 'call_subcallrecord',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallUcdrecord',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('channo', models.IntegerField(null=True, blank=True)),
                ('chantype', models.IntegerField(null=True, blank=True)),
                ('yhbh', models.CharField(max_length=8, blank=True)),
                ('fjh', models.CharField(max_length=8, blank=True)),
                ('flag', models.CharField(max_length=3, blank=True)),
                ('begindatetime', models.CharField(max_length=20, blank=True)),
                ('enddatetime', models.CharField(max_length=20, blank=True)),
                ('durationtime', models.IntegerField(null=True, blank=True)),
                ('ucdgroupid', models.CharField(max_length=4, blank=True)),
                ('export_zt', models.CharField(max_length=1, blank=True)),
                ('chandialno', models.CharField(max_length=20, blank=True)),
                ('callevalue', models.CharField(max_length=2, blank=True)),
                ('compid', models.CharField(max_length=20, blank=True)),
                ('callindatetime', models.CharField(max_length=20, blank=True)),
                ('callno', models.CharField(max_length=50, blank=True)),
            ],
            options={
                'db_table': 'call_ucdrecord',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallUcdrecordSendcfg',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('sfkq', models.CharField(max_length=1)),
                ('url', models.TextField()),
                ('createtime', models.CharField(max_length=20)),
                ('compid', models.CharField(max_length=20, blank=True)),
                ('by1', models.CharField(max_length=20, blank=True)),
                ('by2', models.CharField(max_length=50, blank=True)),
                ('by3', models.CharField(max_length=100, blank=True)),
            ],
            options={
                'db_table': 'call_ucdrecord_sendcfg',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallUcdrecordSendlog',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uuid', models.CharField(max_length=100)),
                ('startid', models.IntegerField(null=True, blank=True)),
                ('endid', models.IntegerField(null=True, blank=True)),
                ('state', models.CharField(max_length=1)),
                ('nr', models.CharField(max_length=200)),
                ('createtime', models.CharField(max_length=20)),
                ('compid', models.CharField(max_length=20, blank=True)),
                ('by1', models.CharField(max_length=20, blank=True)),
                ('by2', models.CharField(max_length=50, blank=True)),
                ('by3', models.CharField(max_length=100, blank=True)),
            ],
            options={
                'db_table': 'call_ucdrecord_sendlog',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallVip',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tel', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'call_vip',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallWxrecord',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('callfromdatetime', models.CharField(max_length=20, blank=True)),
                ('fjh', models.CharField(max_length=20, blank=True)),
                ('zxh', models.CharField(max_length=20, blank=True)),
                ('recordfilename', models.TextField(blank=True)),
                ('recordfilepath', models.TextField(blank=True)),
                ('msgid', models.CharField(max_length=100, blank=True)),
                ('compwxid', models.CharField(max_length=50, blank=True)),
                ('compid', models.CharField(max_length=50, blank=True)),
                ('openid', models.CharField(max_length=50, blank=True)),
                ('msgtype', models.CharField(max_length=50, blank=True)),
                ('voicestatus', models.CharField(max_length=50, blank=True)),
            ],
            options={
                'db_table': 'call_wxrecord',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CallYshmd',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('callno', models.CharField(max_length=10)),
                ('ucdgroupid', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'call_yshmd',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('con_no', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=200, blank=True)),
                ('remark', models.CharField(max_length=20, blank=True)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('paraid', models.CharField(max_length=100, blank=True)),
                ('paravalue', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'config',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ConfmemberRecord',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('confid', models.IntegerField()),
                ('callno', models.CharField(max_length=20, blank=True)),
                ('calltype', models.CharField(max_length=20, blank=True)),
                ('membertype', models.CharField(max_length=20, blank=True)),
                ('membername', models.CharField(max_length=20, blank=True)),
                ('jointime', models.CharField(max_length=20, blank=True)),
                ('quittime', models.CharField(max_length=20, blank=True)),
            ],
            options={
                'db_table': 'confmember_record',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ConfRecord',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('confname', models.CharField(max_length=200, blank=True)),
                ('wstarttime', models.CharField(max_length=20, blank=True)),
                ('wdurationtime', models.CharField(max_length=20, blank=True)),
                ('rstarttime', models.CharField(max_length=20, blank=True)),
                ('rendtime', models.CharField(max_length=20, blank=True)),
                ('runitofstartunit', models.CharField(max_length=2, blank=True)),
                ('rtimeofstart', models.CharField(max_length=20, blank=True)),
                ('rtimeoffinish', models.CharField(max_length=20, blank=True)),
                ('trunkno', models.CharField(max_length=200, blank=True)),
                ('recordfilename', models.CharField(max_length=200, blank=True)),
                ('remark', models.TextField(blank=True)),
                ('rdurationtime', models.CharField(max_length=50, blank=True)),
                ('flag', models.CharField(max_length=1, blank=True)),
            ],
            options={
                'db_table': 'conf_record',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Dual',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('one', models.CharField(max_length=1, blank=True)),
            ],
            options={
                'db_table': 'dual',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ExportRecord',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('guid', models.CharField(max_length=50, blank=True)),
                ('startid', models.IntegerField(null=True, blank=True)),
                ('endid', models.IntegerField(null=True, blank=True)),
                ('flag', models.CharField(max_length=2, blank=True)),
                ('starttime', models.CharField(max_length=20, blank=True)),
                ('endtime', models.CharField(max_length=20, blank=True)),
            ],
            options={
                'db_table': 'export_record',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Operaterecord',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('userid', models.CharField(max_length=20)),
                ('operdatetime', models.CharField(max_length=20)),
                ('opertype', models.CharField(max_length=100, blank=True)),
                ('opersql', models.CharField(max_length=100, blank=True)),
            ],
            options={
                'db_table': 'operaterecord',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Transferplan',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('planid', models.IntegerField()),
                ('recordtype', models.CharField(max_length=2, blank=True)),
                ('transferdate', models.CharField(max_length=100, blank=True)),
                ('transfertime', models.CharField(max_length=20, blank=True)),
                ('transfertype', models.CharField(max_length=2, blank=True)),
                ('transferwhere', models.CharField(max_length=20, blank=True)),
                ('processid', models.CharField(max_length=4, blank=True)),
            ],
            options={
                'db_table': 'transferplan',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Ucdgroup',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ucdgroupid', models.CharField(max_length=4)),
                ('ucdgroupname', models.CharField(max_length=30)),
                ('ucdgroupmemo', models.CharField(max_length=60, blank=True)),
                ('ucdgroupdialno', models.CharField(max_length=4, blank=True)),
                ('ucdgroupenterno', models.CharField(max_length=2, blank=True)),
                ('ucdgrouptruncatetype', models.CharField(max_length=2, blank=True)),
                ('ucdlastuserid', models.IntegerField(null=True, blank=True)),
                ('nowpdrs', models.IntegerField(null=True, blank=True)),
                ('ifopen', models.CharField(max_length=2, blank=True)),
                ('ucdtransfertype', models.CharField(max_length=2, blank=True)),
                ('ucdtransfertime', models.CharField(max_length=20, blank=True)),
                ('ucdtransferwhere', models.CharField(max_length=100, blank=True)),
                ('usecustomercallno', models.CharField(max_length=2, blank=True)),
                ('bussinessgroupid', models.CharField(max_length=4, blank=True)),
            ],
            options={
                'db_table': 'ucdgroup',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Ucdgroupuser',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('yhbh', models.CharField(max_length=8)),
                ('ucdgroupid', models.CharField(max_length=4)),
                ('jtdj', models.CharField(max_length=4, blank=True)),
            ],
            options={
                'db_table': 'ucdgroupuser',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Ucdgroupusernew',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('yhbh', models.CharField(max_length=8)),
                ('ucdgroupid', models.CharField(max_length=4)),
                ('jtdj', models.CharField(max_length=4, blank=True)),
            ],
            options={
                'db_table': 'ucdgroupusernew',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Ucdworkgroup',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('groupid', models.CharField(max_length=4)),
                ('groupname', models.CharField(max_length=20, blank=True)),
            ],
            options={
                'db_table': 'ucdworkgroup',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VeConfrecordQxb',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('userid', models.CharField(max_length=20)),
                ('lx', models.CharField(max_length=20, blank=True)),
                ('hm', models.CharField(max_length=20, blank=True)),
            ],
            options={
                'db_table': 've_confrecord_qxb',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VeQxb',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('yhbh', models.CharField(max_length=8)),
                ('bh', models.CharField(max_length=8)),
                ('fgsbh', models.CharField(max_length=8)),
                ('zdbh', models.CharField(max_length=8)),
                ('sfsc', models.CharField(max_length=1, blank=True)),
                ('sfzj', models.CharField(max_length=1, blank=True)),
                ('sfbc', models.CharField(max_length=1, blank=True)),
                ('sfdy', models.CharField(max_length=1, blank=True)),
                ('sfsh', models.CharField(max_length=1, blank=True)),
                ('sfcx', models.CharField(max_length=1, blank=True)),
                ('tbm', models.CharField(max_length=1, blank=True)),
                ('cplx', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 've_qxb',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VeQxbNew',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('yhbh', models.CharField(max_length=10)),
                ('qxmc', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 've_qxb_new',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VeRecordQxb',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('userid', models.CharField(max_length=20)),
                ('lx', models.CharField(max_length=20, blank=True)),
                ('hm', models.CharField(max_length=20, blank=True)),
            ],
            options={
                'db_table': 've_record_qxb',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VeYhb',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('yhbh', models.CharField(max_length=12)),
                ('mc', models.CharField(max_length=20, blank=True)),
                ('mm', models.CharField(max_length=20, blank=True)),
                ('sffz', models.CharField(max_length=1, blank=True)),
                ('ssz', models.CharField(max_length=8, blank=True)),
                ('fgsbh', models.CharField(max_length=8, blank=True)),
                ('zdbh', models.CharField(max_length=8, blank=True)),
                ('cplx', models.CharField(max_length=4, blank=True)),
                ('ygbh', models.CharField(max_length=8, blank=True)),
                ('zt_yh', models.CharField(max_length=1, blank=True)),
                ('ssxz', models.CharField(max_length=8, blank=True)),
                ('calloutno', models.CharField(max_length=20, blank=True)),
                ('outlineid', models.CharField(max_length=20, blank=True)),
                ('sfzj', models.CharField(max_length=1, blank=True)),
                ('calloutgroup', models.CharField(max_length=4, blank=True)),
                ('switchoutno', models.CharField(max_length=20, blank=True)),
                ('calloutuser', models.CharField(max_length=10, blank=True)),
                ('hhsl', models.CharField(max_length=20, blank=True)),
                ('recordflag', models.CharField(max_length=1, blank=True)),
                ('thsl', models.CharField(max_length=50, blank=True)),
            ],
            options={
                'db_table': 've_yhb',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Voipgroupline',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('extno', models.CharField(max_length=4)),
                ('groupkey', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'voipgroupline',
                'managed': False,
            },
            bases=(models.Model,),
        ),
    ]
